doctrine_migrations:
#    services:
#        'Doctrine\Migrations\Version\MigrationFactory': 'App\Migrations\MigrationFactory'

    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/src/migrations'
